version: '3'
services:
   mongo:
    # container_name: mongodb_database
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongo_dedicated_volume:/data/db

   api_server:
    # container_name: myapp
    build: .
    ports:
      - 3000:3000    

#     environment:
#      URI: mongodb://mongo123/test
#      TOKEN: 5162314638:AAFrt6eYZ1rJxtmyfHzTj9q7_h1-H6ES5Ys

#   #  mongo123:
#   #     image: mongo:latest



      


# volumes:
#   mongo_dedicated_volume: